# Generated by Django 3.0.2 on 2021-02-17 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('postDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('expirySeconds', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('health', 'Health'), ('sport', 'Sport'), ('technology', 'Technology')], max_length=20)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-postDate',),
            },
        ),
    ]
