# Generated by Django 3.0.2 on 2021-02-17 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0004_auto_20210217_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='expiryTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 22, 12, 49, 909932)),
        ),
    ]
