# Generated by Django 3.0.2 on 2021-02-17 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0006_auto_20210217_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='expiryTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
