# Generated by Django 3.0.2 on 2021-02-17 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0007_auto_20210217_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Message is active?'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(verbose_name='Message Body'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='expirySeconds',
            field=models.IntegerField(default=0, verbose_name='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='expiryTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiry time and date'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='postDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
    ]
